name: CMake Build on Win & Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  win:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: amd64

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: build
        run: |
          cmake --build build --config ${{ env.BUILD_TYPE }}

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          echo 'Installing dependencies...'
          sudo apt update
          sudo apt install -y libvulkan-dev vulkan-tools
          sudo apt install -y glslang-tools
          sudo apt install -y libglfw3-dev
          sudo apt install -y libeigen3-dev
          sudo apt install -y libglm-dev

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: build
        run: ctest -C ${{ env.BUILD_TYPE }}
