name: CMake Build on Win & Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Set the desired build type (Release, Debug, etc.)
  BUILD_TYPE: Release

jobs:
  win:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: amd64

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.204.0
          # Include Vulkan-Tools so that glslangValidator.exe is installed.
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Vulkan-Tools
          vulkan-use-cache: true

      - name: Verify Vulkan SDK contents
        # List the contents of the Vulkan SDK Bin directory to ensure glslangValidator.exe is present.
        run: |
          echo "Listing Vulkan SDK Bin directory:"
          ls "$VULKAN_SDK/Bin"

      - name: Add Vulkan SDK Bin to PATH
        run: |
          echo "VULKAN_SDK is $VULKAN_SDK"
          echo "${VULKAN_SDK}\\Bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: |
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libvulkan-dev vulkan-tools glslang-tools
      # Uncomment the lines below if your project depends on these libraries:
      #          sudo apt install -y libglfw3-dev libeigen3-dev libglm-dev

      - name: Configure CMake
        run: |
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DGLFW_BUILD_WAYLAND=ON \
            -DGLFW_BUILD_X11=ON

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: build
        run: ctest -C ${{ env.BUILD_TYPE }}
